include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/check-merge-compatibility.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/sync-to-github.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/python-module-release.yml"

image: 'registry.hpc.ut.ee/mirror/library/python:3.6'

variables:
  GITHUB_OPENNODE_REPO_URL: "git@github.com:opennode/python-freeipa.git"

Run module tests:
  stage: test
  interruptible: true
  rules:
    - if: '$SKIP_TESTS == "true"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pip install -e .[tests]
    - python setup.py test
